version: '3.8'

services:
  visa-tracker:
    build: .
    ports:
      - "5000:5000"
    environment:
      - VISA_TRACKER_EMAIL=${VISA_TRACKER_EMAIL}
      - VISA_TRACKER_PASSWORD=${VISA_TRACKER_PASSWORD}
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
